version: '3'
volumes:
    mongo: 
     driver: local
services:
  database:
    image: mongo:latest
    container_name: mongo-teste-nodejs
    environment:
     MONGO_INITDB_DATABASE: teste-nodejs
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: MongoRootPass!
    volumes:
     - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'
    network_mode: bridge